version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    env_file:
      - .env

  cache:
    container_name: cache
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - ./cache:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: on-failure
    env_file:
      - .env

  app:
    container_name: app
    build: ./
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_DB=${POSTGRES_DB}
      - SPRING_DATASOURCE_PORT=${POSTGRES_CONTAINER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_CONTAINER_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
      - cache